apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2023-06-11T12:37:15Z","generation":2,"labels":{"app":"tripinsights-tripviewer"},"name":"tripinsights-tripviewer","namespace":"default","resourceVersion":"290578","uid":"6d057aac-8c96-4848-9c08-74a538c51719"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"tripinsights-tripviewer"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"tripinsights-tripviewer"}},"spec":{"containers":[{"env":[{"name":"SQL_USER","valueFrom":{"secretKeyRef":{"key":"SQL_USER","name":"sql"}}},{"name":"SQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"SQL_PASSWORD","name":"sql"}}},{"name":"SQL_SERVER","valueFrom":{"secretKeyRef":{"key":"SQL_SERVER","name":"sql"}}},{"name":"SQL_DBNAME","valueFrom":{"secretKeyRef":{"key":"SQL_DBNAME","name":"sql"}}}],"image":"registrydiw3256.azurecr.io/tripinsights/tripviewer:latest","imagePullPolicy":"Always","name":"tripviewer","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2023-06-11T13:18:13Z","lastUpdateTime":"2023-06-11T13:18:13Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-06-11T13:18:13Z","lastUpdateTime":"2023-06-12T08:03:24Z","message":"ReplicaSet \"tripinsights-tripviewer-85cfc47b96\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2023-06-12T08:51:33Z"
  generation: 1
  labels:
    app: tripinsights-tripviewer
  name: tripinsights-tripviewer
  namespace: web-dev
  resourceVersion: "302936"
  uid: 2142c226-cd51-4c6a-a89c-bc46d7c4f5c8
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripinsights-tripviewer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tripinsights-tripviewer
    spec:
      containers:
        - env:
            - name: USERPROFILE_API_ENDPOINT
              value: "http://tripinsights-userprofile"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: TRIPS_API_ENDPOINT
              value: "http://tripinsights-trips"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  key: SQL_USER
                  name: sql
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: sql
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  key: SQL_SERVER
                  name: sql
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  key: SQL_DBNAME
                  name: sql
          image: registrydiw3256.azurecr.io/tripinsights/tripviewer:latest
          imagePullPolicy: Always
          name: tripviewer
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2023-06-12T08:51:35Z"
      lastUpdateTime: "2023-06-12T08:51:35Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-06-12T08:51:33Z"
      lastUpdateTime: "2023-06-12T08:51:35Z"
      message: ReplicaSet "tripinsights-tripviewer-8ff5d8ff" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
