apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-12T19:14:58Z"
  labels:
    app: tripinsights-tripviewer
  name: tripinsights-tripviewer
  namespace: web
  resourceVersion: "10211"
  uid: c47c98aa-05ff-4516-b749-4e52c7640f4f
spec:
  clusterIP: 10.0.146.238
  clusterIPs:
  - 10.0.146.238
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripinsights-tripviewer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
