apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trip-viewer-ingress
  namespace: ingress
  annotations:
    kubernetes.io/ingress.class: "{{CHANGEME - nginx|addon-http-application-routing|etc}}"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tripinsights-tripviewer
                port:
                  number: 80
