
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web_writer
  namespace: web
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api_writer
  namespace: api
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "watch", "list", "update"]


