apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-12T19:15:19Z"
  labels:
    app: tripinsights-user-java
  name: tripinsights-user-java
  namespace: api
  resourceVersion: "10288"
  uid: 970b9aa5-f7b1-4b05-8ca9-2fb3730bf704
spec:
  clusterIP: 10.0.113.4
  clusterIPs:
  - 10.0.113.4
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripinsights-user-java
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
