apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
  creationTimestamp: "2023-06-11T12:37:06Z"
  generation: 11
  labels:
    app: tripinsights-trips
  name: tripinsights-trips
  namespace: default
  resourceVersion: "287101"
  uid: b244322c-58b8-4c8f-83ba-50ddced98cdc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripinsights-trips
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tripinsights-trips
    spec:
      containers:
      - env:
        - name: DEBUG_LOGGING
          value: "true"
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              key: SQL_USER
              name: sql
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: SQL_PASSWORD
              name: sql
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              key: SQL_SERVER
              name: sql
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              key: SQL_DBNAME
              name: sql
        image: registrydiw3256.azurecr.io/tripinsights/trips:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        name: trips
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-11T13:19:19Z"
    lastUpdateTime: "2023-06-12T07:48:31Z"
    message: ReplicaSet "tripinsights-trips-5d745596fc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-06-12T07:49:19Z"
    lastUpdateTime: "2023-06-12T07:49:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
