apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    name: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"    
  labels:
    app: tripinsights-trips
  name: tripinsights-trips
  namespace: api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripinsights-trips
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tripinsights-trips
    spec:
      containers:
      - env:
        - name: DEBUG_LOGGING
          value: "true"
        image: registrydiw3256.azurecr.io/tripinsights/trips:latest
        imagePullPolicy: Always
        name: trips
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: keyvault-secret-sql-user
          mountPath: /etc/secrets/sql-user
          readOnly: true
        - name: keyvault-secret-sql-password
          mountPath: /etc/secrets/sql-password
          readOnly: true
        - name: keyvault-secret-sql-server
          mountPath: /etc/secrets/sql-server
          readOnly: true
        - name: keyvault-secret-sql-db-name
          mountPath: /etc/secrets/sql-db-name
          readOnly: true
      volumes:
      - name: keyvault-secret-sql-user
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: team-six-secrets
          options:
            keyvaultname: "TeamSixSecrets"
            keyvaultobjectname: "SQLUSER" 
            newkeyname: "sql-user.txt"
      - name: keyvault-secret-sql-password
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: team-six-secrets
          options:
            keyvaultname: "TeamSixSecrets"
            keyvaultobjectname: "SQLPASSWORD"
            newkeyname: "sql-password.txt"
      - name: keyvault-secret-sql-server
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: team-six-secrets
          options:
            keyvaultname: "TeamSixSecrets"
            keyvaultobjectname: "SQLSERVER"
            newkeyname: "sql-server.txt"
      - name: keyvault-secret-sql-db-name
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: team-six-secrets
          options:
            keyvaultname: "TeamSixSecrets"
            keyvaultobjectname: "SQLDBNAME"
            newkeyname: "sql-db-name.txt"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
