apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    name: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: tripinsights-trips
  name: tripinsights-trips
  namespace: api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripinsights-trips
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tripinsights-trips
    spec:
      containers:
        - env:
            - name: DEBUG_LOGGING
              value: "true"
          image: registrydiw3256.azurecr.io/tripinsights/trips:latest
          imagePullPolicy: Always
          name: trips
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: keyvault-secret-sql
              mountPath: "/mnt/secrets"
              readOnly: true
      volumes:
        - name: keyvault-secret-sql
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "keyvault-trips"
        - name: keyvault-secret-sql-password
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
