apiVersion: v1
kind: Namespace
metadata:
  name: api
  labels:
    name: api

---
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: tripinsights-poi
  name: tripinsights-poi
  namespace: api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripinsights-poi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tripinsights-poi
    spec:
      containers:
        - image: registrydiw3256.azurecr.io/tripinsights/poi:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          name: poi
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: DEMO_FAREWELL
              value: "Such a sweet sorrow"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  key: SQL_USER
                  name: sql
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: sql
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  key: SQL_SERVER
                  name: sql
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  key: SQL_DBNAME
                  name: sql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
