# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-11T13:04:05Z"
  generation: 1
  labels:
    app: tripinsights-poi
  name: tripinsights-poi
  namespace: api-dev
  resourceVersion: "13392"
  uid: 6080576e-6d71-4c45-9412-2c1ae469c67b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tripinsights-poi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tripinsights-poi
    spec:
      containers:
        - image: registrydiw3256.azurecr.io/tripinsights/poi:latest
          ports:
          - containerPort: 80
          imagePullPolicy: Always
          name: poi
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DEMO_GREETING
              value: "Hello from the environment"
            - name: DEMO_FAREWELL
              value: "Such a sweet sorrow"
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  key: SQL_USER
                  name: sql
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SQL_PASSWORD
                  name: sql
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  key: SQL_SERVER
                  name: sql
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  key: SQL_DBNAME
                  name: sql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2023-06-11T13:15:27Z"
      lastUpdateTime: "2023-06-11T13:15:27Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-06-11T13:15:27Z"
      lastUpdateTime: "2023-06-11T13:15:27Z"
      message: ReplicaSet "tripinsights-poi-66f788cfbb" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
