apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-12T08:21:18Z"
  labels:
    app: tripinsights-poi
  name: tripinsights-poi
  namespace: default
  resourceVersion: "295185"
  uid: eecaa971-66e2-41fe-b859-63fab4a78f90
spec:
  clusterIP: 10.0.226.86
  clusterIPs:
  - 10.0.226.86
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripinsights-poi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
