apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-12T19:14:07Z"
  labels:
    app: tripinsights-poi
  name: tripinsights-poi
  namespace: api
  resourceVersion: "10018"
  uid: 66093d4e-9466-4022-83bc-f6bd6ee38abe
spec:
  clusterIP: 10.0.34.115
  clusterIPs:
  - 10.0.34.115
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: tripinsights-poi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
